### ISSUE TITLE
Different sensor names on languages other than English

### ISSUE THREAD

**Issue by etcho** [amaximus/transmission-card#45]
I was struggling for some time trying to understand why my card couldn't read information from the sensor, even though I could add torrents using the text field on the card. The sensors worked just fine, but the card couldn't see them.

Searching on `transmission-card.js` for "no sensor" (the only information I was able to get from the card), I ended up discovering that the card expects a sensor named `transmission_download_speed`. What I didn't notice was that my Portuguese installation of hass translated the sensor names when I installed the transmission integration. So, almost all of the transmission sensors were written in Portuguese, which obviously causes issues with the card. So I looked for the original sensor names on the official page of the transmission's integration and changed them, and everything worked just fine.

I know the problem was on my side, but from an user's point of view, it can be hard to notice this kind of thing. Adding the possibility to set the name of all sensors separately on the card configuration could be a solution, but doesn't sound very practical. If this information (that the sensor names must be the same as the official English names) was displayed on the `readme.md` I think it would help a lot during the troubleshooting process.

**Comment by amaximus** [comment]
Thanks for your information. The custom card does not expect English names, however by default uses the English name the Transmission component originally generated.
As HA evolved and introduced generating entity names localized, the generated names became different from the default English name. The `sensor_name` was meant to solve this issue. The readme of the card describes that the default sensor_name is transmission. So if your instance is localized and HA or the component generates entity names accordingly then you'll have to use the `sensor_name`.
I'll review the readme and clarify if needed.

**Comment by luixal** [comment]
Hi,

Sorry to bump this issue but I just hit this... and I don't think it was solved.

I had a look at the `sensor_entity_id` but if I've understood it well, it doesn't solve the problem as it is related to the suffix rather than the sensor name.

Looking into the code, for example at [this line](https://github.com/amaximus/transmission-card/blob/197e9da8a28b4205566a5e1cb6746457d4065724/transmission-card.js#L124):

```js
let download_speed = `sensor.${this.config.sensor_entity_id}_download_speed`;
```
doesn't solve this as my sensor (in spanish) is called `sensor.transmission_velocidad_de_descarga` instead of `sensor.transmission_download_speed`. The main "name" is the same, `transmission` but the suffix is the piece that changes.

As I possible solution I only see adding the fields to specify each sensor manually.

PS: the solution I'm using right now is renaming entities IDs to match the ones in english.

**Comment by etcho** [comment]
@luixal, the solution that worked for me also was change all the sensor names for the English ones. It's the easiest workaround until a more elegant solution comes up.
